name: Compile LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: actions/setup-latex@v1

      - name: Compile LaTeX document
        run: pdflatex main.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: main.pdf
